Repository famura/SimuRLacra, pull requests merged in 2021-08, with the labels that each got.

#81 Add a gym wrapper for pysim envs
  .github/codecov.yml
  Pyrado/pyrado/environments/pysim/__init__.py
  Pyrado/pyrado/environments/pysim/gym_wrapper.py
  Pyrado/tests/test_environments.py
  README.md
Labels: enhancement

#82 Don't mark non-static methods as static.
  Pyrado/pyrado/algorithms/episodic/nes.py
  Pyrado/pyrado/algorithms/episodic/sysid_via_episodic_rl.py
  Pyrado/pyrado/algorithms/meta/bayrn.py
  Pyrado/pyrado/algorithms/meta/sbi_base.py
  Pyrado/pyrado/algorithms/meta/simopt.py
  Pyrado/pyrado/algorithms/regression/nonlin_regression.py
  Pyrado/pyrado/algorithms/step_based/a2c.py
  Pyrado/pyrado/algorithms/step_based/dql.py
  Pyrado/pyrado/algorithms/step_based/ppo.py
  Pyrado/pyrado/algorithms/step_based/sac.py
  Pyrado/pyrado/domain_randomization/domain_parameter.py
  Pyrado/pyrado/domain_randomization/transformations.py
  Pyrado/pyrado/environments/one_step/two_dim_gaussian.py
  Pyrado/pyrado/environments/pysim/gym_wrapper.py
  Pyrado/pyrado/exploration/stochastic_action.py
  Pyrado/pyrado/utils/data_sets.py
  Pyrado/pyrado/utils/experiments.py
  Pyrado/scripts/evaluation/paper_specific/npdr_eval_posterior_prob_mg.py
  Pyrado/tests/algorithms/test_meta.py
Labels: bug fix

#85 Fix evaluation pipeline for deterministic samplers
  Pyrado/pyrado/sampling/parallel_evaluation.py
  Pyrado/pyrado/sampling/parallel_rollout_sampler.py
  Pyrado/pyrado/sampling/parameter_exploration_sampler.py
  Pyrado/pyrado/sampling/sampler_pool.py
  Pyrado/scripts/evaluation/eval_policy_domain_grid_nd.py
Labels: bug fix

#86 Fixed experiment loading for experiment w/o extra information but a SLURM ID
  Pyrado/pyrado/logger/experiment.py
Labels: bug fix

#89 Also render documentation for __init__ methods
  Pyrado/doc/source/conf.py
Labels: documentation
