Repository famura/SimuRLacra, pull requests merged in 2021-05, with the labels that each got.

#48 Fix experiment loading for SPRL
  Pyrado/pyrado/algorithms/utils.py
  Pyrado/pyrado/utils/experiments.py
Labels: bug

#49 Allow the usage of WrappedSampler
  Pyrado/pyrado/algorithms/utils.py
Labels: bug

#51 Adapted check_all_equal for dicts with np arrays and added tests
  Pyrado/pyrado/utils/checks.py
  Pyrado/tests/test_utils.py
Labels: bug

#53 Build docs in separate workflow
  .github/workflows/publish_docker.yml
  .github/workflows/publish_docs.yml
Labels: bug

#54 Skip tests in CI based on high_memory
  .github/workflows/run_tests.yml
  Pyrado/tests/algorithms/test_meta.py
  Pyrado/tests/pytest.ini
Labels: enhancement

#55 Fixed error that ParameterExploring, LQR, and BayRn where not pickleable.
  Pyrado/pyrado/algorithms/episodic/parameter_exploring.py
  Pyrado/pyrado/algorithms/episodic/predefined_lqr.py
  Pyrado/pyrado/algorithms/meta/bayrn.py
Labels: bug fix

#56 Implemented packed padded seq for two headed rnn
  Pyrado/pyrado/policies/recurrent/rnn.py
  Pyrado/pyrado/policies/recurrent/two_headed_rnn.py
  Pyrado/tests/test_policies.py
Labels: enhancement

#58 Fix type error when using SAC
  Pyrado/pyrado/algorithms/step_based/gae.py
  Pyrado/pyrado/algorithms/step_based/sac.py
Labels: bug fix

#59 Fixed that sampling hangs for large neural networks policies.
  Pyrado/pyrado/policies/recurrent/neural_fields.py
  Pyrado/pyrado/sampling/parallel_rollout_sampler.py
  Pyrado/pyrado/sampling/parameter_exploration_sampler.py
Labels: bug fix

#61 Do not clean gh-pages branch when pushing new docs
  .github/workflows/publish_docs.yml
Labels: bug fix, documentation

#62 Readd index page for documentation
  index.html
  logo.png
Labels: bug fix, documentation

#65 Include information on `--headless` parameter.
  README.md
Labels: documentation
